services:
  db:
    image: mariadb:10.11
    container_name: podcast-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME:-podcast_db}
      MARIADB_USER: ${DB_USER:-podcast_user}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  podcast-app:
    build: .
    container_name: podcast-generator
    depends_on:
      - db
    ports:
      - "7860:7860"
    environment:
      - PYTHONPATH=/app
      - HOST=0.0.0.0
      - PORT=7860
      - DB_HOST=db  # Verweist auf den 'db' Service oben
      - DB_PORT=3306
      - API_KEY=${API_KEY}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/google-credentials.json
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./Output:/app/Output
      - ${GOOGLE_KEY_LOCAL_PATH}:/app/google-credentials.json
    restart: unless-stopped

volumes:
  db_data:
  data:
  Output:
